# Generated by Django 2.2 on 2020-06-06 21:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('price', models.IntegerField()),
                ('qty_sold', models.IntegerField()),
                ('qty_available', models.IntegerField()),
                ('is_sale', models.BooleanField(default=False)),
                ('is_bestSeller', models.BooleanField(default=False)),
                ('is_newArrival', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('is_published', models.TextField(default=True)),
                ('rating', models.IntegerField()),
                ('star', models.IntegerField()),
                ('product_date', models.DateTimeField(default=datetime.datetime.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.Category')),
            ],
        ),
    ]
