# Generated by Django 2.2 on 2020-06-07 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200607_0315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='star',
        ),
    ]
