# Generated by Django 2.2 on 2020-06-07 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stars',
        ),
    ]
